-- liquibase formatted sql

-- changeset jinothomas:4	
CREATE TABLE USLS_USERS
(
	USER_ID UUID NOT NULL,
	ROLE_ID BIGINT NOT NULL,
	NAME CHARACTER VARYING NOT NULL,
	EMAIL CHARACTER VARYING NOT NULL,
	MOBILE_NUMBER CHARACTER VARYING,
	USER_STATUS CHARACTER VARYING,
	CREATED_BY CHARACTER VARYING,
	LAST_MODIFIED_BY CHARACTER VARYING,
	CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
	LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE,
	CONSTRAINT PK_ID PRIMARY KEY(USER_ID),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES USLS_ROLES(ID)
);