-- liquibase formatted sql

-- changeset jinothomas:1	
CREATE TABLE USLS_GROUPS
(
	ID SERIAL PRIMARY KEY,
	NAME CHARACTER VARYING NOT NULL,
	STATUS CHARACTER VARYING NOT NULL,
	ACTIVE_DATE_FROM TIMESTAMP WITHOUT TIME ZONE,
	ACTIVE_DATE_TO TIMESTAMP WITHOUT TIME ZONE,
	CREATED_BY CHARACTER VARYING,
	LAST_MODIFIED_BY CHARACTER VARYING,
	CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
	LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE
);