-- liquibase formatted sql

-- changeset jinothomas:2
CREATE TABLE USLS_ROLES
(
	ID SERIAL PRIMARY KEY,
	NAME CHARACTER VARYING NOT NULL,
	GROUP_ID BIGINT NOT NULL,
	PRIORITY INT NOT NULL ,
	STATUS CHARACTER VARYING NOT NULL,
	CREATED_BY CHARACTER VARYING,
	LAST_MODIFIED_BY CHARACTER VARYING,
	CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
	LAST_MODIFIED_DATE TIMESTAMP WITHOUT TIME ZONE,
	CONSTRAINT FK_GROUP FOREIGN KEY(GROUP_ID) REFERENCES USLS_GROUPS(ID)
);