-- liquibase formatted sql

-- changeset jinothomas:5	
INSERT INTO USLS_GROUPS (NAME,STATUS,ACTIVE_DATE_FROM,CREATED_BY,CREATED_DATE) VALUES ('SYSTEM_MANAGER','ACTIVE','2000-01-01','SYSTEM','2000-01-01');
INSERT INTO USLS_ROLES (NAME,GROUP_ID,PRIORITY,STATUS,CREATED_BY,CREATED_DATE) VALUES ('SYSTEM_ADMIN',1,1,'ACTIVE','SYSTEM','2000-01-01');
INSERT INTO USLS_PERMISSIONS (NAME,TYPE,ROLE_ID,DESCRIPTION,CREATED_BY,CREATED_DATE) VALUES ('API_SYSTEM_ALL_OPS','ALL_OPS',1,'All System APIs','SYSTEM','2000-01-01');
INSERT INTO USLS_PERMISSIONS (NAME,TYPE,ROLE_ID,DESCRIPTION,CREATED_BY,CREATED_DATE) VALUES ('UI_SYSTEM_ALL_OPS','ALL_OPS',1,'All System UI','SYSTEM','2000-01-01');